name: Deploy Website via FTP

on:
  push:
    branches:
      - main # Set this to your default branch name (main or master)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /httpd/www/luciendelmar.com/html/inglis/
          local-dir: ./ # Uploads everything from the repository
          # exclude: |  # Uncomment and add files to exclude if needed
          #   .git*/**
          #   .git*
          #   **/.git*/**
          #   **/.git*
          #   .github/**
          #   README.md
